-- RUN THIS IN SUPABASE SQL EDITOR
-- This script safely inserts the original 4 hardcoded trips into your Supabase database 
-- so they can finally be managed from the Admin Dashboard.

INSERT INTO public.trips (
    name, tagline, description, region, terrain, duration, price, group_size, image_url, status, is_featured, itinerary, inclusions
) VALUES 
('Spiti Valley', 'Silence, altitude, and shared roads', 'This journey exists because some roads deserve patience. Because high-altitude deserts teach you things flat lands never will.', 'North India', 'Moderate', 9, 28999, 10, '/trips/spiti-hero.jpg', 'published', true, '[{"day": 1, "title": "Arrival", "description": "Shimla to Narkanda. The mountains begin."}, {"day": 2, "title": "Ascent", "description": "Chitkul, Kalpa, and the Kinnaur valleys. Altitude adjusts your priorities."}, {"day": 3, "title": "Stillness", "description": "Kaza, Key, and Kibber. The heart of Spiti. Time stops making sense."}, {"day": 4, "title": "Return", "description": "Kunzum Pass, Chandratal, and the descent. You leave different."}]'::jsonb, '["All accommodation", "Breakfast & dinner", "Transport in tempo traveller", "Local experiences", "Experienced trip lead"]'::jsonb),

('Ladakh Circuit', 'Where the sky meets the earth', 'Because Ladakh isn''t a destination, it''s a reckoning. The kind of place that makes you question what you thought you knew about beauty, about space, about yourself.', 'North India', 'Challenging', 11, 38999, 10, '/trips/ladakh-hero.jpg', 'published', true, '[{"day": 1, "title": "Arrival", "description": "Leh. Acclimatization. Let your body catch up with your excitement."}, {"day": 2, "title": "Ascent", "description": "Khardung La, Nubra Valley. The highest roads on earth."}, {"day": 3, "title": "Stillness", "description": "Pangong Lake. Blue that doesn''t exist elsewhere. Silence that speaks."}, {"day": 4, "title": "Return", "description": "Tso Moriri, and the long way back. Changed."}]'::jsonb, '["All accommodation", "All meals", "Innova/Tempo transport", "Permits", "Oxygen backup", "Experienced trip lead"]'::jsonb),

('Kerala Backwaters', 'Slow rivers, slower days', 'Because speed is overrated. Because floating through life for a few days teaches you to stop rushing. Because the backwaters of Kerala hold stories in their stillness.', 'South India', 'Easy', 6, 22999, 12, '/trips/kerala-hero.jpg', 'published', true, '[{"day": 1, "title": "Arrival", "description": "Kochi. Colonial history meets spice markets. Fort Kochi sunsets."}, {"day": 2, "title": "Ascent", "description": "Munnar. Tea estates that roll forever. Cool mountain air."}, {"day": 3, "title": "Stillness", "description": "Alleppey. Houseboats and hammocks. The pace of water."}, {"day": 4, "title": "Return", "description": "Varkala cliffs. One last sunset over the Arabian Sea."}]'::jsonb, '["All accommodation including houseboat", "Breakfast", "All transport", "Kathakali show", "Spice plantation visit"]'::jsonb),

('Meghalaya Trails', 'Clouds below, roots above', 'Because living root bridges aren''t just engineering marvels—they''re lessons in patience. Because the wettest place on earth has learned to live with rain, not fight it.', 'North East India', 'Moderate', 7, 25999, 10, '/trips/meghalaya-hero.jpg', 'published', true, '[{"day": 1, "title": "Arrival", "description": "Shillong. The Scotland of the East. Music in the hills."}, {"day": 2, "title": "Ascent", "description": "Cherrapunji. Living root bridges. Ancient lessons in sustainability."}, {"day": 3, "title": "Stillness", "description": "Dawki. Crystal rivers. The border with Bangladesh."}, {"day": 4, "title": "Return", "description": "Mawlynnong. Asia''s cleanest village. Simple lessons."}]'::jsonb, '["All accommodation", "Breakfast & dinner", "Sumo transport", "Guide fees", "Living root bridge trek"]'::jsonb);

SELECT 'Successfully Seeded The 4 Original Trips into Supabase!' AS result;
